# vim: nospell
#
language: minimal
dist: xenial

cache:
  timeout: 600
  directories:
    - $HOME/.stack/snapshots
    - $HOME/.local/bin
    - .stack-work/install

before_cache:
  # - rm -vrf $(stack path --local-install-root)/bin
  - rm -rf  $(stack path --local-install-root)/doc

addons:
  apt:
    sources: &apt_sources
      - hvr-ghc

    packages: &apt_packages
      - alex-3.1.7
      - happy-1.19.5
      - libgmp-dev

matrix:
  fast_finish: true
  include:
    - env: GHC=8.6.4
      compiler: "GHC 8.6"

    - env: GHC=8.4.3
      compiler: "GHC 8.4"

    - env: GHC=8.2.2
      compiler: "GHC 8.2"

    - env: GHC=8.0.2
      compiler: "GHC 8.0"

    # - env: GHC=head CABAL=head
    #   compiler: "GHC HEAD"
    #   addons: { apt: { sources: [ hvr-ghc ], packages: [ ghc-head, cabal-install-head, happy-1.19.5, alex-3.1.7 ] }}

  # allow_failures:
  #   - env: GHC=head CABAL=head

before_install:
  - export PATH=/opt/alex/3.1.7/bin:/opt/happy/1.19.5/bin:${PATH}
  - source .travis/install-stack.sh
  - |
      case ${GHC%.*} in
        8.0) ;; # too slow ._.
        *  ) export HADDOCK="--haddock --no-haddock-deps" ;;
      esac

  # build environment
  - echo "$(stack exec ghc -- --version) [$(stack exec ghc -- --print-project-git-commit-id 2> /dev/null || echo '?')]"
  - stack --version

install:
  - export FLAGS="--jobs=2 --no-terminal --no-copy-bins --flag accelerate:nofib"
  - travis_retry stack build $FLAGS --only-dependencies --test

script:
  - stack build $FLAGS $HADDOCK --test --no-run-tests
  - stack test accelerate:doctest --flag accelerate:nofib
  - stack test accelerate:nofib-interpreter --test-arguments='--hedgehog-tests 25' --flag accelerate:nofib

after_success:
  - source .travis/update-accelerate-buildbot.sh

